services:
  mysql-one:
    container_name: database-one
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=springbatch
      - MYSQL_ROOT_PASSWORD=root

  mysql-two:
    container_name: database-two
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=springbatch
      - MYSQL_ROOT_PASSWORD=root
